### ISSUE TITLE
[REQUEST] feature Nefarious container stack

### ISSUE THREAD

**Issue by bycytov** [novaspirit/pi-hosted#115]
I have a request to please add nefarious web app to the app templates so it can be installed directly through portainer

here is the link
https://github.com/lardbit/nefarious

Hopefully this could be added soon as I have been having trouble getting this working on my arm device

**Comment by Griffen8280** [comment]
Nefarious can be pulled and started directly from their github in portainer.  If you click on the "Stacks" button under your local instance.  Then click on the "+ Add Stack" button there you will find it has the ability to pull the git repository directly and build the project using the docker-compose.yml file in the repo.  I deployed this to my pi-hosted instance through this method and it is fully functional after following the directions.  Unfortunately I don't beleive we can make a simple template out of this project that can be pulled through the template interface due to the complexity of the build and install required in this project.  @rmiddle may have more insight as to what can be done though.

**Comment by bycytov** [comment]
Hey just tried it out and I think I got it working. Unfortunately I still can’t get it configured the way I wanted it too. I pasted the git link but I’m not sure how to get transmission-ovpn properly configured. Also can’t figure out how to change the download location. Did you use docker-compose.yml or docker-compose.transmission-vpn.yml file? If I use the docker-compose.base.yml I can get all the services running but it’s not VPN. Can I just get the stack running start a separate transmission-ovpn container than get nefarious to talk with that one and just delete the regular transmission? If possible can you tell me step by step how you got it running?

**Comment by Griffen8280** [comment]
yeah I just used the main docker-compose.yml to see if it would run and everything fired right up.  And yes you could do some modifying to the system even after it is running.  Just blow away the transmission container and startup the transmission-ovpn one and point the nefarious settings to it instead.  Or when you do the pull in the stack area you can specify which docker compose file to use.  So instead of using the docker-compose.yml (default) tell it to use docker-compose.transmission-vpn.yml instead and the whole stack should be built with the vpn integrated automagically.  There may be some minor tweaking you'll have to do once its all up and running but looking at the compose file it should work.

**Comment by rmiddle** [comment]
It could be done it looks like it would require at least 2 stacks maybe more.  At least 1 with the VPN and 1 without.  It not outside the scope of the project but I just don't have time to do it myself.  If someone were to come up with a patch I would certainly test it out and work at getting it push through.
