### ISSUE TITLE
Bookstack Redirect me to my wan ip and another port

### ISSUE THREAD

**Issue by ChristKe** [novaspirit/pi-hosted#207]
**Question**
Why is this happening
**Context**
Here is the log from Bookstack

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 01-envfile: executing... ,
[cont-init.d] 01-envfile: exited 0.,
[cont-init.d] 10-adduser: executing... ,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
-------------------------------------,
,
To support LSIO projects visit:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    1001,
User gid:    1001,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 20-config: executing... ,
[cont-init.d] 20-config: exited 0.,
[cont-init.d] 30-keygen: executing... ,
using keys found in /config/keys,
[cont-init.d] 30-keygen: exited 0.,
[cont-init.d] 50-config: executing... ,
New container detected. Setting up app folder and fixing permissions.,
App Key found - setting variable for seds,
Running config - db_user set,
**** Docker env var APP_URL is not set, setting it to http://*.*.*.210:6875 ****,  **## the local ip of my Rpi4 is 192.168.31.202 and the port that i define for Bookstack when i deploy the stack :3101** 
/var/run/s6/etc/cont-init.d/50-config: line 97: warning: command substitution: ignored null byte in input,
/var/run/s6/etc/cont-init.d/50-config: line 97: warning: command substitution: ignored null byte in input,
Nothing to migrate.,
[cont-init.d] 50-config: exited 0.,
[cont-init.d] 90-custom-folders: executing... ,
[cont-init.d] 90-custom-folders: exited 0.,
[cont-init.d] 99-custom-files: executing... ,
[custom-init] no custom files found exiting...,
[cont-init.d] 99-custom-files: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.

**Comment by anotherglitchinthematrix** [comment]
I've encountered the very same problem when I put my bookstack behind a reverse proxy, I've deployed other versions but the issue was persistent across different images. You also have noticed the source of the issue, the missing `APP_URL` environment variable, when I set it to fit my needs as `APP_URL=stack.mydomain.com` the problem was solved. I suggest you the same, set the missing environment variable as `APP_URL=192.168.31.202:3101` and the issue should be fixed. I don't know if it was documented but the detailed logs was really helpful.

**Comment by ChristKe** [comment]
I also tried to add this missing env variable but the error was exactly the same. When i hit my local ip redirect me to wan with 6875 port... 
I delete everything from portainer and the local folders of Bookstack and redeploy but error persist.

**Comment by anotherglitchinthematrix** [comment]
Well, it seems the linuxservers image is somehow buggy, also I forgot to add, APP_URL must be defined with protocol like `APP_URL=https://stack.myproxy.com`, I've derived the original docker-compose file like in the example below, could you test it like this?

```yaml
---
version: "2"
services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=https://stack.myproxy.com/
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=yourdbpass
      - DB_DATABASE=bookstackapp
    volumes:
      - /path/to/data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
      
  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=yourdbpass
      - TZ=Europe/London
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=yourdbpass
    volumes:
      - /path/to/data:/config
    restart: unless-stopped
```

**Comment by ChristKe** [comment]
Hi there! 
I finally got the time for testing, your solution helped me a lot. I used your docker-compose file and worked like charm! 
Many thanks @anotherglitchinthematrix !!!
